export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCY_DATA = 'GET_CURRENCY_DATA';
export const GET_CURRENCY_HISTORY = 'GET_CURRENCY_HISTORY';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';
export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE';
export const CHANGE_COLOR = 'CHANGE_COLOR';
export const FILTER_CURRENCIES = 'FILTER_CURRENCIES';
export const UNFILTER_CURRENCIES = 'UNFILTER_CURRENCIES';
